export const ADMIN_PAGE_ROUTE = '/admin'
export const MAIN_PAGE_ROUTE = '/'
export const WATCHLIST_ROUTE = '/watchlist'
export const REVIEW_PAGE_ROUTE = '/review'
export const CREATE_NEW_PROJECT_PAGE = '/newProject'